Feature_Attack:
  model_name: "magic"
  base_url: "http://127.0.0.1:8080/predictions/magic"
  threshold_type: '100fpr'              # '100fpr' or '1000fpr'
  IDA_PATH: "The path to the directory containing idaq64."
  SCRIPT_PATH: "../scripts/graph_handle_acfg.py"
  tmp_sample_root: "../dataset/tmp"
  no_last_call: False
  seed: 23
  mcts_levels: 6
  mcts_scalar: 0
  num_workers: 80
  call_block_limit: 0                     # 把call_block数小于等于call_block_limit的都过滤掉
  gen_features_strategy: 'random'         # 在新块中插指令的方式
  max_random_number: 200                  # 插入每类指令的最大条数
  mcts_pause_time: 300                     # mcts限制时间 (s)
  attack_strategy: 'mcts'                 # random / mcts
  mcts_budget: 40                         # 
  attempt_alpha: 3
  attempt_beta: 5
  selected_semnop_num: 3
  mcts_default_policy_search_depth: 1     # default_policy中找块的深度
  rate_of_increasement: 0.01
  if_size_align: False
  device : 'cuda'

Problem_Attack:
  ML:
    model_name: "malgraph"
    base_url: "http://127.0.0.1:8080/predictions/magic"
    threshold_type: '100fpr'              # '100fpr' or '1000fpr'
  AV:
    model_name: "mcafee"
  clsf_list: ['kaspersky']
  target_pattern: "AV"
  attack_strategy: 'mcts'
  tmp_sample_root: "../dataset/tmp"
  muti_sections: False
  mcts_levels: 6
  mcts_scalar: 0
  num_workers: 10
  max_random_number: 300
  mcts_pause_time: 600
  mcts_budget: 30
  attempt_alpha: 1
  attempt_beta: 1
  selected_semnop_num: 3
  mcts_default_policy_search_depth: 1
  rate_of_increasement: 0.05
Training:
  cuda: True                              # enable GPU training if cuda is available
  dist_backend: "nccl"                    # if using torch.distribution, the backend to be used
  dist_port: "1234"
  max_epoches: 10
  train_batch_size: 16
  test_batch_size: 32
  seed: 19920208
  only_test_path: 'None'
Model:
  gnn_type: "GCN"                         # "GraphSAGE" / "GCN"
  pool_type: "global_max_pool"            # "global_max_pool" / "global_mean_pool"
  acfg_init_dims: 11
  cfg_filters: "128-256-384-256"          # 目标模型的卷积层结构
  num_classes: 1
  dropout_rate: 0.5
  use_activation: True                    # 这个参数在使用grad攻击的时候要改成False，因为加了激活函数不好优化
  last_activation: "sigmoid"
  model_path: "None"    # 目标模型的路径
Acfg:
  num_workers: 80
  IDA_PATH: "The path to the directory containing idaq64."
  SCRIPT_PATH: "../scripts/graph_handle_acfg.py"
  patch_script_path: "../scripts/processing_patch_by_ida.py"
  # 提acfg的时候这后面几个参数一定要改
  get_half_data: False
  hash_to_path: "../scripts/hash_list/mal_hash_to_path.txt"
  saved_path: "../scripts/extracted_data/0529/val/val_mal_acfg_files_before_call"
  hash_list: "../scripts/hash_list/val_mal_hash.txt"